### ISSUE TITLE
להוסיף טסטים - כל אחד בדברים שהוא עשה

### ISSUE THREAD

**Issue by EllaSheory** [ICST-Technion/WelliBe#19]

**Comment by shaiTheKimhi** [comment]
הוספתי מחלקת mock ל-database, יש סוגיה אחת שאני אשמח אם מישהו יוכל לעזור לי לשבת עליה, אני צריך לדעת מה פורמט הפלט של השאילתות על AuthService ו-Users/Doctors Collection, אנחנו צריכים להחליף אותם לתוצאה קבועה ואז יהיה פשוט להריץ טסטים.
